### ISSUE TITLE
文档内没有看到怎么部署的？可以介绍下吗？也想参与这个项目

### ISSUE THREAD

**Issue by D-zz** [cloustone/sentel#2]

**Comment by cloustone** [comment]
The deployment is not current focus now, we will improve deployment in next month.
You can use docker-compose for base service now.
For example docker-comple -f scripts/docker-compose-base-service.yaml up to start base service.
and then, start apiserver, or broker or whaler to debug it.
In next phase, we will use docker-swarm as our scrum deployment tools to confirm distributed architecture, and Then, kubernetes for production environment.
Now, we are confirming data flows between apiserver->broker->whaler.

# An invitation had been sent to you, you can enjoy sentel and improve it.

**Comment by D-zz** [comment]
Thanks very much，I will continue to pay attention to it，Hope to make a contribution
