### ISSUE TITLE
ERROR:make docker GOOS=linux 

### ISSUE THREAD

**Issue by D-zz** [cloustone/sentel#3]
USE Mac os
when make docker GOOS=linux 
docker build -f iothub/nginx-mqtt/Dockerfile .
Sending build context to Docker daemon  476.6MB
Step 1/9 : FROM centos
 ---> 2d194b392dd1
Step 2/9 : COPY iotgateway/nginx-mqtt/nginx.repo /etc/yum.repos.d/
COPY failed: stat /var/lib/docker/tmp/docker-builder696979447/iotgateway/nginx-mqtt/nginx.repo: no such file or directory
make: *** [docker] Error 1

Don`t have iotgateway,I guess it is iothub？

**Comment by cloustone** [comment]
Please pull again, the files had been updated. Thanks
